---
title: "Auditory Stimuli Profiling"
output: html_document
---
# Set up
```{r setup}
library(tidyverse)
library(mgsub)
library(ggplot2)
library(patchwork)

read_table_transposed <- function(table_file, measure){
  table_df <- read.table(table_file, header=T) %>%
    pivot_longer(cols=-1, names_to = "token_label", values_to = measure) %>% select(-1) %>%
    mutate(speaker_dir = str_split(table_file, '/')[[1]][6])
}

read_table_normtime <- function(table_file, measure, formant=FALSE){
  table_df <- read.table(table_file, header=T) %>%
    pivot_longer(cols=-1, names_to = "normtime", values_to = measure) %>%
    mutate(speaker_dir = str_split(table_file, '/')[[1]][6])
  
  if (formant==FALSE){
    table_df <- table_df %>% select(-1)
  } else {
    table_df <- table_df %>% extract(1, into=c("formant"), regex="(?:.*?_){3}(.+)$")
  # separate(1, into=c(NA, NA, NA, "formant"), sep = "_", extra="merge") # same effect
  }
}
```

```{r}
token_info %>% names(.)
```


# Speaker Set-up
```{r}
token_info <- list.files("../02-stimuli/P0-norming/n2/03-recordings",
           pattern="selected_tokens_info.csv", recursive=TRUE, 
           full.names = TRUE) %>%
  plyr::ldply(., read_csv) %>% 
  mutate(variable = case_when(variableN == 1 ~ "PIN-PEN",
                              variableN == 2 ~ "FEEL-FILL",
                              variableN == 3 ~ "TH-stopping",
                              variableN == 4 ~ "OU-backing",
                              variableN == 5 ~ "U-fronting",
                              variableN == 6 ~ "AEN-raising",
                              variableN == 7 ~ "AE-backing",
                              variableN == 8 ~ "T-deletion"),
         phone = case_when(variableN == 1 ~ "EH1",
                            variableN == 2 ~ "IY1",
                            variableN == 3 ~ "DH",
                            variableN == 4 ~ "OW1",
                            variableN == 5 ~ "UW1",
                            variableN == 6 ~ "AE1",
                            variableN == 7 ~ "AE1",
                            variableN == 8 ~ "T"),
         .before=word)
token_info

# Version of token_info with 10 reps per token row for normed data
norm_token_info <- token_info %>% slice(rep(1:n(), each = 10))
norm_token_info

speaker_list <- token_info %>% distinct(speaker) %>% pull()
```

# Word-level
## Duration
```{r}
# Read in data
w_dur_df <- list.files("../02-stimuli/P0-norming/n2/03-recordings",
           pattern="duration.txt",  recursive=TRUE, full.names = TRUE) %>%
  stringr::str_subset(., "word_level", negate = FALSE) %>%
   plyr::ldply(., read_table_transposed, "duration") %>%
  cbind(token_info, .) %>% 
  mutate(token_label = gsub(".1", "", token_label, fixed=TRUE))

# Check row match
w_dur_df %>% filter(word !=token_label) %>% nrow()
w_dur_df %>% filter(speaker !=speaker_dir) %>% nrow()

# Finalize data
( w_dur_df <- w_dur_df %>% select(-token_label, -speaker_dir) )

# Plot grand means
w_dur_df %>%
  ggplot(aes(x=variant, y=duration)) + theme_minimal() +
  stat_summary(geom="pointrange")

# Plot means across speaker per variable
w_dur_df %>%
  ggplot(aes(x=variableN, y=duration, linetype=variant, color=variable)) + theme_minimal() +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)

# Plot by-speaker means per variable
for (spk_num in speaker_list){
  plot <- w_dur_df %>% filter(speaker==spk_num) %>%
  ggplot(aes(x=variableN, y=duration, linetype=variant, color=variable)) + theme_minimal() + facet_wrap(~speaker) +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)
 print(plot)
}

```

## F0 
### Mean
```{r}
w_meanf0_df <- list.files("../02-stimuli/P0-norming/n2/03-recordings",
           pattern="meanf0.txt",  recursive=TRUE, full.names = TRUE) %>%
  stringr::str_subset(., "word_level", negate = FALSE) %>%
   plyr::ldply(., read_table_transposed, "meanf0") %>%
  cbind(token_info, .) %>% 
  mutate(token_label = gsub(".1", "", token_label, fixed=TRUE))

# Check row match
w_meanf0_df %>% filter(word !=token_label) %>% nrow()
w_meanf0_df %>% filter(speaker !=speaker_dir) %>% nrow()

# Finalize data
( w_meanf0_df <- w_meanf0_df %>% select(-token_label, -speaker_dir) )

# Plot grand means
w_meanf0_df %>%
  ggplot(aes(x=variant, y=meanf0)) + theme_minimal() +
  stat_summary(geom="pointrange")

w_meanf0_df %>%
  ggplot(aes(x=variableN, y=meanf0, linetype=variant, color=variable)) + theme_minimal() +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)

# Plot by-speaker means per variable
for (spk_num in speaker_list){
  plot <- w_meanf0_df %>% filter(speaker==spk_num) %>%
  ggplot(aes(x=variableN, y=meanf0, linetype=variant, color=variable)) + theme_minimal() + facet_wrap(~speaker) +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)
 print(plot)
}
```

### Max
```{r}
w_maxf0_df <- list.files("../02-stimuli/P0-norming/n2/03-recordings",
           pattern="maxf0.txt",  recursive=TRUE, full.names = TRUE) %>%
  stringr::str_subset(., "word_level", negate = FALSE) %>%
   plyr::ldply(., read_table_transposed, "maxf0") %>%
  cbind(token_info, .) %>% 
  mutate(token_label = gsub(".1", "", token_label, fixed=TRUE))

# Check row match
w_maxf0_df %>% filter(word !=token_label) %>% nrow()
w_maxf0_df %>% filter(speaker !=speaker_dir) %>% nrow()

# Finalize data
( w_maxf0_df <- w_maxf0_df %>% select(-token_label, -speaker_dir) )

# Plot grand means
w_maxf0_df %>%
  ggplot(aes(x=variant, y=maxf0)) + theme_minimal() +
  stat_summary(geom="pointrange")

w_maxf0_df %>%
  ggplot(aes(x=variableN, y=maxf0, linetype=variant, color=variable)) + theme_minimal() +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)

# Plot by-speaker means per variable
for (spk_num in speaker_list){
  plot <- w_maxf0_df %>% filter(speaker==spk_num) %>%
  ggplot(aes(x=variableN, y=maxf0, linetype=variant, color=variable)) + theme_minimal() + facet_wrap(~speaker) +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)
 print(plot)
}
```

### Min
```{r}
w_minf0_df <- list.files("../02-stimuli/P0-norming/n2/03-recordings",
           pattern="minf0.txt",  recursive=TRUE, full.names = TRUE) %>%
  stringr::str_subset(., "word_level", negate = FALSE) %>%
   plyr::ldply(., read_table_transposed, "minf0") %>%
  cbind(token_info, .) %>% 
  mutate(token_label = gsub(".1", "", token_label, fixed=TRUE))

# Check row match
w_minf0_df %>% filter(word !=token_label) %>% nrow()
w_minf0_df %>% filter(speaker !=speaker_dir) %>% nrow()

# Finalize data
( w_minf0_df <- w_minf0_df %>% select(-token_label, -speaker_dir) )

# Plot grand means
w_minf0_df %>%
  ggplot(aes(x=variant, y=minf0)) + theme_minimal() +
  stat_summary(geom="pointrange")

w_minf0_df %>%
  ggplot(aes(x=variableN, y=minf0, linetype=variant, color=variable)) + theme_minimal() +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)

# Plot by-speaker means per variable
for (spk_num in speaker_list){
  plot <- w_minf0_df %>% filter(speaker==spk_num) %>%
  ggplot(aes(x=variableN, y=minf0, linetype=variant, color=variable)) + theme_minimal() + facet_wrap(~speaker) +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)
 print(plot)
}
```

### Final
```{r}
w_finalf0_df <- list.files("../02-stimuli/P0-norming/n2/03-recordings",
           pattern="finalf0.txt",  recursive=TRUE, full.names = TRUE) %>%
  stringr::str_subset(., "word_level", negate = FALSE) %>%
   plyr::ldply(., read_table_transposed, "finalf0") %>%
  cbind(token_info, .) %>% 
  mutate(token_label = gsub(".1", "", token_label, fixed=TRUE))

# Check row match
w_finalf0_df %>% filter(word !=token_label) %>% nrow()
w_finalf0_df %>% filter(speaker !=speaker_dir) %>% nrow()

# Finalize data
( w_finalf0_df <- w_finalf0_df %>% select(-token_label, -speaker_dir) )

# Plot grand means
w_finalf0_df %>%
  ggplot(aes(x=variant, y=finalf0)) + theme_minimal() +
  stat_summary(geom="pointrange")

w_finalf0_df %>%
  ggplot(aes(x=variableN, y=finalf0, linetype=variant, color=variable)) + theme_minimal() +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)

# Plot by-speaker means per variable
for (spk_num in speaker_list){
  plot <- w_finalf0_df %>% filter(speaker==spk_num) %>%
  ggplot(aes(x=variableN, y=finalf0, linetype=variant, color=variable)) + theme_minimal() + facet_wrap(~speaker) +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)
 print(plot)
}
```

### Normalized
```{r}
w_normf0_df <- list.files("../02-stimuli/P0-norming/n2/03-recordings",
           pattern="normf0.txt",  recursive=TRUE, full.names = TRUE) %>%
  stringr::str_subset(., "word_level", negate = FALSE) %>%
   plyr::ldply(., read_table_normtime, "normf0") %>%
  cbind(norm_token_info, .) %>%
  mutate(timepoint = rep(1:10, length.out=n())) %>%
  relocate(timepoint, normf0, .before=normtime)
w_normf0_df

# Check row match
w_normf0_df %>% filter(speaker !=speaker_dir) %>% nrow()

# Finalize data
( w_normf0_df <- w_normf0_df %>% select(-normtime, -speaker_dir) )
```

#### All Speakers
```{r}
# Grand means across all speakers
# Across all tokens
w_normf0_df %>%
  ggplot(aes(x=timepoint, y=normf0)) + theme_minimal() +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  stat_summary(geom="smooth", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(2, 9), breaks=2:9)

# Between-variant comparison (across all variables)
w_normf0_df %>%
  ggplot(aes(x=timepoint, y=normf0, col=variant)) + theme_minimal() +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge()) +
  stat_summary(geom="smooth", position=position_dodge()) +
  scale_x_continuous(limits = c(2, 9), breaks=2:9)

# By variable + between-variant comparison
w_normf0_df %>%
  ggplot(aes(x=timepoint, y=normf0, col=variant)) + theme_minimal() + facet_wrap(~variableN) +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge()) +
  stat_summary(geom="smooth", position=position_dodge()) +
  scale_x_continuous(limits = c(2, 9), breaks=2:9)
```

#### By-Speaker
```{r}
for (spk_num in speaker_list){
  plot <- w_normf0_df %>% filter(speaker==spk_num) %>%
  # Across all tokens
    ggplot(aes(x=timepoint, y=normf0)) + theme_minimal() + facet_wrap(~speaker) +
    # geom_point(alpha=0.2) +
    # stat_summary(geom="col", alpha=0.5, position="dodge") +
    stat_summary(geom="pointrange", position=position_dodge(0.95)) +
    stat_summary(geom="smooth", position=position_dodge(0.95)) +
    scale_x_continuous(limits = c(2, 9), breaks=2:9)
   print(plot)
   
  # Between-variant comparison (across all variables)
  plot <- w_normf0_df %>% filter(speaker==spk_num) %>%
    ggplot(aes(x=timepoint, y=normf0, col=variant)) + theme_minimal() + facet_wrap(~speaker) +
    # geom_point(alpha=0.2) +
    # stat_summary(geom="col", alpha=0.5, position="dodge") +
    stat_summary(geom="pointrange", position=position_dodge()) +
    stat_summary(geom="smooth", position=position_dodge()) +
    scale_x_continuous(limits = c(2, 9), breaks=2:9)
   print(plot)
   
  # By variable + between-variant comparison
  plot <- w_normf0_df %>% filter(speaker==spk_num) %>%
    ggplot(aes(x=timepoint, y=normf0, col=variant)) + theme_minimal() + facet_wrap(~speaker) + facet_wrap(~variableN) +
    # geom_point(alpha=0.2) +
    # stat_summary(geom="col", alpha=0.5, position="dodge") +
    stat_summary(geom="pointrange", position=position_dodge()) +
    stat_summary(geom="smooth", position=position_dodge()) +
    scale_x_continuous(limits = c(2, 9), breaks=2:9)
 print(plot)
}

```

#### By-Variable for Speaker
```{r, fig.width=12, fig.height=6}
current_speaker = speaker_list[[1]]
exclude_rows = c()

for (var_num in c(1:8)){
  plot1 <- w_normf0_df %>% filter(speaker==current_speaker) %>%
    filter(variableN==var_num) %>%
    filter((!rowN %in% exclude_rows)) %>%
    ggplot(aes(x=timepoint, y=normf0, col=variant)) + theme_minimal() + facet_wrap(~variable) +
    stat_summary(geom="pointrange", position=position_dodge()) +
    stat_summary(geom="line", position=position_dodge()) +
    # stat_summary(geom="smooth", position=position_dodge()) +
    scale_x_continuous(limits = c(2, 9), breaks=2:9) +
    labs(title="Average across Tokens")

  plot2 <- w_normf0_df  %>% filter(speaker==current_speaker) %>%
    filter(variableN==var_num) %>% 
    filter((!rowN %in% exclude_rows)) %>%
    ggplot(aes(x=timepoint, y=normf0, col=variant)) + theme_minimal() + 
    facet_wrap(~rowN, ncol = 5) +
    geom_point() +
    geom_line() +
    # geom_smooth() +
    scale_x_continuous(limits = c(1, 10), breaks=2:9) +
    labs(title="By-Token")
  
  combined_plot <- plot1 + plot2 + 
    plot_layout(guides = "collect") +
    plot_annotation(title = paste0(current_speaker, " - Variable ",var_num))
  print(combined_plot)
}

```



#### [TBD] Identify Tokens to Fix (Manually)
```{r}
# Identify all tokens with outlier f0 values for any timepoint
# Produce a list of those tokens per speaker
# Go in and manually adjust those before re-running pitch extraction
```
```{r}
# normf0_df %>% group_by(speaker,item_code,variableN,rowN, variantN, word,variant) %>% 
#   summarize(
#   # meanf0=mean(normf0), 
#   sdf0=sd(normf0)
#   ) %>%
#   full_join(normf0_df,.) %>% 
#   # mutate(diffmeanf0=normf0-meanf0) %>%
#   filter(sdf0<50)
# 
# normf0_steps <- 
#   normf0_df %>% select(-normtime) %>% filter(timepoint!=10) %>% rename(timepoint_1=timepoint, normf0_1=normf0) %>%
#   cbind(
#     normf0_df %>% select(-normtime) %>% filter(timepoint!=1) %>% select(timepoint_2=timepoint, normf0_2=normf0) 
#   ) %>%
#   mutate(
#     timepoint_stepdiff = paste(timepoint_1, timepoint_2, sep='-'),
#     f0_stepdiff = normf0_2-normf0_1, .after=variant)
# 
# normf0_steps %>%  filter(abs(f0_stepdiff) > 20)
# 
# normf0_steps %>% filter(item_code=="3.3.1")

```


# Phone-level

## Duration
```{r}
# Read in data
p_dur_df <- list.files("../02-stimuli/P0-norming/n2/03-recordings",
           pattern="duration.txt",  recursive=TRUE, full.names = TRUE) %>%
  stringr::str_subset(., "phone_level", negate = FALSE) %>%
   plyr::ldply(., read_table_transposed, "duration") %>%
  cbind(token_info, .) %>% 
  mutate(token_label = mgsub(token_label, "\\.[0-9]+$", "", fixed=FALSE))

# Check row match
p_dur_df %>% filter(phone !=token_label) %>% nrow()
p_dur_df %>% filter(speaker !=speaker_dir) %>% nrow()

# Finalize data
( p_dur_df <- p_dur_df %>% select(-token_label, -speaker_dir) )

# Plot grand means
p_dur_df %>%
  ggplot(aes(x=variant, y=duration)) + theme_minimal() +
  stat_summary(geom="pointrange")

# Plot means across speaker per variable
p_dur_df %>%
  ggplot(aes(x=variableN, y=duration, linetype=variant, color=variable)) + theme_minimal() +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)

# Plot by-speaker means per variable
for (spk_num in speaker_list){
  plot <- p_dur_df %>% filter(speaker==spk_num) %>%
  ggplot(aes(x=variableN, y=duration, linetype=variant, color=variable)) + theme_minimal() + facet_wrap(~speaker) +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(0, 9), breaks=1:8)
 print(plot)
}

```

## Formants
### Normalized
```{r}
read.table("/Users/laurettacheng/Documents/Projects/SpAAC/02-materials/02-stimuli/P0-norming/n2/03-recordings/S01/3_selections/1_P1/5_profiled/phone_level/normtime_formant.txt", header=T) %>%
    pivot_longer(cols=-1, names_to = "normtime", values_to = "normform") %>%
    extract(1, into=c("formant"), regex="(?:.*?_){3}(.+)$")
  # separate(1, into=c(NA, NA, NA, "formant"), sep = "_", extra="merge") # same effect
  

```


```{r}
w_normform_df <- list.files("../02-stimuli/P0-norming/n2/03-recordings",
           pattern="normtime_formant.txt",  recursive=TRUE, full.names = TRUE) %>%
  stringr::str_subset(., "phone_level", negate = FALSE) %>%
   plyr::ldply(., read_table_normtime, "normform", formant=TRUE) %>%
  arrange(formant) %>%
  cbind(norm_token_info %>% slice(rep(1:n(), times=4)), .) %>%
  mutate(timepoint = rep(1:10, length.out=n())) %>%
  relocate(timepoint, normform, .before=normtime)
w_normform_df

# Check row match
w_normform_df %>% filter(speaker !=speaker_dir) %>% nrow()

# Finalize data
( w_normform_df <- w_normform_df %>% select(-normtime, -speaker_dir) %>%
    filter(formant!="F2_3") %>% filter(!variableN %in% c(3, 8)))
```


#### All Speakers
```{r}
# Grand means across all speakers
# Across all tokens
w_normform_df %>%
  ggplot(aes(x=timepoint, y=normform, linetype=formant)) + theme_minimal() +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge(0.95)) +
  stat_summary(geom="smooth", position=position_dodge(0.95)) +
  scale_x_continuous(limits = c(2, 9), breaks=2:9)

# Between-variant comparison (across all variables)
w_normform_df %>%
  ggplot(aes(x=timepoint, y=normform, col=variant, linetype=formant)) + theme_minimal() +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge()) +
  stat_summary(geom="smooth", position=position_dodge()) +
  scale_x_continuous(limits = c(2, 9), breaks=2:9)

# By variable + between-variant comparison
w_normform_df %>%
  ggplot(aes(x=timepoint, y=normform, col=variant, linetype=formant)) + theme_minimal() + facet_wrap(~variable) +
  # geom_point(alpha=0.2) +
  # stat_summary(geom="col", alpha=0.5, position="dodge") +
  stat_summary(geom="pointrange", position=position_dodge()) +
  stat_summary(geom="smooth", position=position_dodge()) +
  scale_x_continuous(limits = c(2, 9), breaks=2:9)
```

#### By-Speaker
```{r, fig.width=7, fig.height=6}
for (spk_num in speaker_list){

  # By variable + between-variant comparison
  plot <- w_normform_df %>% filter(speaker==spk_num) %>%
    ggplot(aes(x=timepoint, y=normform, col=variant, linetype=formant)) + theme_minimal() + facet_wrap(~speaker) + facet_wrap(~variable) +
    # geom_point(alpha=0.2) +
    # stat_summary(geom="col", alpha=0.5, position="dodge") +
    stat_summary(geom="pointrange", position=position_dodge()) +
    stat_summary(geom="smooth", position=position_dodge()) +
    scale_x_continuous(limits = c(2, 9), breaks=2:9) +
    labs(title= paste0(spk_num))
    print(plot)
}

```

#### By-Variable for Speaker
```{r, fig.width=12, fig.height=6}
current_speaker = speaker_list[[1]]
variable_list = w_normform_df %>% distinct(variableN) %>% pull()
exclude_rows = c()

for (var_num in variable_list){
  plot_df <- w_normform_df %>% filter(speaker==current_speaker) %>% 
    filter(formant!="F3") %>%
    filter(variableN==var_num) %>%  filter((!rowN %in% exclude_rows))  
  
  plot1 <- plot_df %>%
    ggplot(aes(x=timepoint, y=normform, col=variant, linetype=formant)) + theme_minimal() + facet_wrap(~variable) +
    stat_summary(geom="pointrange", position=position_dodge()) +
    stat_summary(geom="line", position=position_dodge()) +
    # stat_summary(geom="smooth", position=position_dodge()) +
    scale_x_continuous(limits = c(2, 9), breaks=2:9) +
    labs(title="Average across Tokens")

  plot2 <- plot_df %>%
    ggplot(aes(x=timepoint, y=normform, col=variant, linetype=formant)) + theme_minimal() + 
    facet_wrap(~rowN, ncol = 5) +
    geom_point() +
    geom_line() +
    # geom_smooth() +
    scale_x_continuous(limits = c(1, 10), breaks=2:9) +
    labs(title="By-Token")
  
  combined_plot <- plot1 + plot2 + 
    plot_layout(guides = "collect") +
    plot_annotation(title = paste0(current_speaker, " - Variable ",var_num))
  print(combined_plot)
}

```
